scope: cfdigital

metadata:
  name: recipe-sharing
  labels:
    scope: recipe-sharing
    app: recipe-sharing
    name: recipe-sharing
    role: recipe-sharing
    environment: dev

spec:
  replicas: 1
  template:
    spec:
      restartPolicy: Always
      imagePullSecrets:
        name: secret-nexus

container:
  name: recipe-sharing
  image:
    repository: recipe-sharing
    tag: latest
  imagePullPolicy: IfNotPresent
  ports:
    server:
      name: server
      containerPort: 8081
    actuator:
      name: actuator
      containerPort: 9091
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 9091
    initialDelaySeconds: 5
    periodSeconds: 15
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 10
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 9091
    initialDelaySeconds: 5
    periodSeconds: 30
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 10

service:
  headless:
    metadata:
      name: recipe-sharing-headless
    spec:
      ports:
        server:
          name: server
          port: 8081
          targetPort: 8081
  client:
    metadata:
      name: recipe-sharing-client
    spec:
      ports:
        server:
          name: server
          port: 8081
          targetPort: 8081
        actuator:
          name: actuator
          port: 1080
          targetPort: 1080

hpa:
  spec:
    scaleTargetRef:
      name: recipe-sharing
    minReplicas: 1
    maxReplicas: 2
    metrics:
      cpuAverageUtilization: 60

configmap:
  metadata:
    name: recipe-sharing
  data:
    javaopts: Xms128m -Xmx256m
