apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headless.metadata.name }}
  labels:
    app: {{ .Values.metadata.labels.app }}
    name: {{ .Values.metadata.labels.name }}
    role: {{ .Values.metadata.labels.role }}
    environment: {{ .Values.metadata.labels.environment }}
spec:
  ports:
    - port: {{ .Values.service.headless.spec.ports.server.port }}
      name: {{ .Values.service.headless.spec.ports.server.name }}
      targetPort: {{ .Values.service.headless.spec.ports.server.targetPort }}
  clusterIP: None
  selector:
    app: {{ .Values.metadata.labels.app }}
