apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.client.metadata.name }}
  labels:
    app: {{ .Values.metadata.labels.app }}
    name: {{ .Values.metadata.labels.name }}
    role: {{ .Values.metadata.labels.role }}
    environment: {{ .Values.metadata.labels.environment }}
spec:
  ports:
    - port: {{ .Values.service.client.spec.ports.server.port }}
      name: {{ .Values.service.client.spec.ports.server.name }}
      targetPort: {{ .Values.service.client.spec.ports.server.targetPort }}
    - port: {{ .Values.service.client.spec.ports.actuator.port }}
      name: {{ .Values.service.client.spec.ports.actuator.name }}
      targetPort: {{ .Values.service.client.spec.ports.actuator.targetPort }}
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: {{ .Values.metadata.labels.app }}